# coding=utf-8
import os.path

import tornado
from bokeh.util.browser import view

from bokeh_server.handlers import routes


class Application(tornado.web.Application):
    def __init__(self):
        settings = dict(
            template_path=os.path.join(os.path.dirname(__file__), "templates"),
            static_path=os.path.join(os.path.dirname(__file__), "static"),
            xsrf_cookies=True,
            # NOTE: some random value as secret (i.e. generated by uuid4())
            cookie_secret="YOUR SECRET HERE",
            login_url="/auth/login",
            debug=True,
        )
        super(Application, self).__init__(routes, **settings)


def server(host="localhost", port=5002):
    http_server = tornado.httpserver.HTTPServer(Application())
    http_server.listen(address=host, port=port)
    io_loop = tornado.ioloop.IOLoop.current()

    io_loop.add_callback(view, "http://{h}:{p}/app1".format(h=host, p=port))
    io_loop.add_callback(view, "http://{h}:{p}/app2".format(h=host, p=port))

    io_loop.start()


if __name__ == '__main__':
    server()
